### PR TITLE
add docker labels to all logs shipped to LogzIO

### PR DESCRIPTION
**Pull request by jeffreykoetsier**
Updated version of docker-loghose allows docker labels to be added to every logentry being send to LogzIO.

### CODE REVIEW

**Comment by idohalevi** [comment]
@jeffreykoetsier 
Hi, sorry for the late response I've been a bit busy. I will go over it today/tomorrow.
In the meanwhile, Can you please add a description to the readme

**Comment by jeffreykoetsier** [comment]
Hi,

Thanks! I've updated the README.

**Comment by idohalevi** [comment]
@jeffreykoetsier 
LGTM. Thank you for the PR!

**Comment by jeffreykoetsier** [comment]
Thanks! Will this automatically publish a new version on dockerhub?

https://hub.docker.com/r/logzio/logzio-docker/tags/

**Comment by idohalevi** [comment]
@jeffreykoetsier I will publish it by the end of the day

**Pull request merged**
